.build/test_obj/serial_link_transport/./quantum/serial_link/tests/transport_tests.o: \
 quantum/serial_link/tests/transport_tests.cpp \
 quantum/serial_link/protocol/transport.h \
 quantum/serial_link/protocol/triple_buffered_object.h \
 quantum/serial_link/system/serial_link.h tmk_core/common/host_driver.h \
 tmk_core/common/report.h tmk_core/common/keycode.h
quantum/serial_link/protocol/transport.h:
quantum/serial_link/protocol/triple_buffered_object.h:
quantum/serial_link/system/serial_link.h:
tmk_core/common/host_driver.h:
tmk_core/common/report.h:
tmk_core/common/keycode.h:
