/* This file was generated by `qmk generate-keyboard-h`. Do not edit or copy.
 */

#pragma once
#include "quantum.h"
#pragma error("<keyboard>.h is only optional for data driven keyboards - kb.h == bad times")
