/* This file was generated by `qmk generate-config-h`. Do not edit or copy.
 */

#pragma once

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0009
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION TIBrownAlps
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION ROW2COL
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER "Texas Instrument"
#endif // MANUFACTURER

#ifndef PRODUCT
#   define PRODUCT "TI Alps SKCM Brown"
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x6969
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0xFEED
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 16
#endif // MATRIX_COLS

#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 8
#endif // MATRIX_ROWS


#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { F7, F6, F5, F4, F3, F2, F1, F0, E7, B0, E6, C0, E1, E0, D7, D5 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { B7, D0, D1, D2, B6, B5, B4, B3 }
#endif // MATRIX_ROW_PINS
