.build/test_obj/serial_link_byte_stuffer/./quantum/serial_link/tests/byte_stuffer_tests.o: \
 quantum/serial_link/tests/byte_stuffer_tests.cpp \
 quantum/serial_link/protocol/byte_stuffer.h \
 quantum/serial_link/protocol/frame_validator.h \
 quantum/serial_link/protocol/physical.h
quantum/serial_link/protocol/byte_stuffer.h:
quantum/serial_link/protocol/frame_validator.h:
quantum/serial_link/protocol/physical.h:
