# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= halfkay
MCU ?= at90usb1286
MOUSEKEY_ENABLE ?= yes
BOOTMAGIC_ENABLE ?= yes
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= no
COMMAND_ENABLE ?= no
NKRO_ENABLE ?= yes
AUDIO_ENABLE ?= yes
