#include QMK_KEYBOARD_H

#define _____ KC_TRNS
#define XXXXX KC_NO
#define _L0 0
#define _L1 1

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[_L0] = LAYOUT_all(
		KC_F4, KC_F5, KC_F12, KC_P4, KC_NUM, KC_VOLD, KC_MUTE, KC_LGUI, CK_TOGG, KC_SPC, KC_B, KC_J, KC_Y, KC_6, KC_INS, KC_RALT, 
		KC_F3, KC_F6, KC_F11, KC_P5, KC_PSLS, KC_VOLU, KC_MPLY, KC_PSCR, KC_MPRV, KC_SPC, KC_SPC, KC_NUBS, KC_EQL, KC_HOME, KC_LALT, 
		KC_F2, KC_F7, KC_F10, KC_P6, KC_PAST, KC_TAB, KC_A, KC_ESC, KC_MNXT, KC_BSPC, KC_ENT, KC_RBRC, KC_MINS, KC_GRV, KC_LCTL, 
		KC_F1, KC_F8, KC_F9, KC_P3, KC_PMNS, KC_Q, KC_S, KC_1, KC_P0, KC_SLSH, KC_BSLS, KC_LBRC, KC_0, KC_DEL, KC_MSTP, 
		KC_F16, KC_F17, KC_F24, KC_P2, KC_P7, KC_W, KC_D, KC_2, KC_Z, KC_LEFT, KC_DOT, KC_QUOT, KC_P, KC_9, KC_END, KC_RSFT, 
		KC_F15, KC_F18, KC_F23, KC_P1, KC_P8, KC_E, KC_F, KC_3, KC_X, KC_LGUI, KC_COMM, KC_SCLN, KC_O, KC_8, KC_PGUP, KC_LSFT, 
		KC_F14, KC_F19, KC_F22, KC_PDOT, KC_P9, KC_R, KC_G, KC_4, KC_C, KC_DOWN, KC_M, KC_L, KC_I, KC_7, KC_PGDN, 
		KC_F13, KC_F20, KC_F21, KC_PENT, KC_PPLS, KC_T, KC_H, KC_5, KC_V, KC_RGHT, KC_N, KC_K, KC_U, KC_RCTL, KC_UP, KC_CAPS),

[_L1] = LAYOUT_all(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

};

/*
void matrix_init_user(void) {

  setPinOutput(B5);
  writePinHigh(B5);

  setPinOutput(B6);
  writePinHigh(B6);

  setPinOutput(B4);
  writePinHigh(B4);
}

bool led_update_kb(led_t led_state) {
    bool res = led_update_user(led_state);
    if(res) {
        writePin(B5, led_state.num_lock);
        writePin(B6, led_state.caps_lock);
        writePin(B4, led_state.scroll_lock);
    }
    return res;
}
*/
