#include QMK_KEYBOARD_H

#define _____ KC_TRNS
#define XXXXX KC_NO
#define _L0 0
#define _L1 1

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[_L0] = LAYOUT_all(
		KC_UP, KC_LEFT, KC_LGUI, KC_RGHT, KC_DOWN, KC_LALT, KC_P5, KC_P2, KC_PGDN, LCTL(LSFT(KC_TAB)), KC_PENT, KC_SPC, KC_PPLS, KC_PMNS, KC_PAST, 
		KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_PEQL, KC_P8, KC_PGUP, KC_PGDN, KC_PDOT, KC_P3, KC_P6, KC_P9, KC_PSLS, 
		KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_LGUI, KC_END, KC_END, KC_HOME, KC_DEL, KC_P0, KC_P1, KC_P4, KC_P7, KC_NLCK, 
		KC_RSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, MO(1), KC_PGDN, KC_END, KC_RCTL, KC_SPC, 
		KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_DEL, KC_MNXT, KC_BSLS, KC_ENT, KC_QUOT, 
		KC_LALT, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_MPRV, KC_SPC, KC_RBRC, KC_LBRC, KC_P, 
		KC_CAPS, KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_DEL, KC_BSPC, KC_EQL, KC_MINS, KC_0, 
		KC_LCTL, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_MPLY, KC_PSCR, KC_GRV, KC_F12, KC_F11),

[_L1] = LAYOUT_all(
		LCTL(LSFT(KC_T)), LCTL(LSFT(KC_TAB)), LCTL(KC_F), LCTL(KC_TAB), LCTL(KC_W), KC_TRNS, KC_TRNS, KC_TRNS, KC_MNXT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPRV, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPLY, KC_TRNS, KC_MSTP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_RALT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RCTL, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLU, KC_NUBS, KC_APP, KC_TRNS, 
		KC_TRNS, RESET, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_PWR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_F13, KC_F14, KC_F15, KC_F16, KC_F17, KC_F18, KC_F19, KC_F20, KC_F21, KC_F22, KC_MUTE, KC_INS, KC_PAUS, KC_F24, KC_F23)

};

void matrix_init_user(void) {

  setPinOutput(B2);
  writePinHigh(B2);
}

bool led_update_kb(led_t led_state) {
    bool res = led_update_user(led_state);
    if(res) {
        writePin(B2, led_state.caps_lock);
    }
    return res;
}
