/* This file was generated by `qmk generate-config-h`. Do not edit or copy.
 */

#pragma once

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0002
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION PanasonicBusinessPartner286
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION ROW2COL
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER "Panasonic"
#endif // MANUFACTURER

#ifndef PRODUCT
#   define PRODUCT "Business Partner 286"
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x6969
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0xFEED
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 16
#endif // MATRIX_COLS

#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 8
#endif // MATRIX_ROWS


#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { C7, C6, C5, C4, C3, C2, C1, C0, E1, E0, D7, F0, B1, B0, E6, E7 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { B3, D5, D4, D3, D2, D1, D0, B7 }
#endif // MATRIX_ROW_PINS
