.build/test_obj/serial_link_frame_router/./quantum/serial_link/tests/frame_router_tests.o: \
 quantum/serial_link/tests/frame_router_tests.cpp \
 quantum/serial_link/protocol/transport.h \
 quantum/serial_link/protocol/triple_buffered_object.h \
 quantum/serial_link/system/serial_link.h tmk_core/common/host_driver.h \
 tmk_core/common/report.h tmk_core/common/keycode.h \
 quantum/serial_link/protocol/byte_stuffer.h \
 quantum/serial_link/protocol/frame_router.h
quantum/serial_link/protocol/transport.h:
quantum/serial_link/protocol/triple_buffered_object.h:
quantum/serial_link/system/serial_link.h:
tmk_core/common/host_driver.h:
tmk_core/common/report.h:
tmk_core/common/keycode.h:
quantum/serial_link/protocol/byte_stuffer.h:
quantum/serial_link/protocol/frame_router.h:
